### ISSUE TITLE
Google Drive download is broken

### ISSUE THREAD

**Issue by Otoris** [Ashok0/HL2VREssentials#1]
https://puu.sh/JlTak/a07fef7543.png

Unfortunately will need a mirror or popularity to die down. If anyone has a mirror please share.

**Comment by GitHubUsername1** [comment]
Please provide a mirror link.

**Comment by TIE-INTERCEPTOR** [comment]
Found an alternative link. Get jdownloader2 http://jdownloader.org/jdownloader2 ,  install it, then get https://t.co/gvIp9BRZZV < this download link, open it with jdownloader and you are good to go, it will download it... it's huge 17,9 gb , so patience.

**Comment by KrisSodroski** [comment]
Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.

Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.

**Comment by TIE-INTERCEPTOR** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 

it's straight up from the discord of the guys making the mods, you can check for yourself. It might look dodgy as f but I tried it and it worked. Anyway,

you can check the thread on the help on the flatscreen to VR discord >
https://discord.com/channels/747967102895390741/1020466377032728647

**Comment by jTiKey** [comment]
can someone just torrent this

**Comment by webhead2oo9** [comment]
I'm hosting both files for now, I'll pull if I have to bandwidth wise, but seems manageable so far.

https://vrdiscord.com/HL2VR_MO2.rar
https://vrdiscord.com/EP12Assets.rar

**Comment by Ashok0** [comment]
Download links have been moved to a new host.
