### ISSUE TITLE
Game is detected as Half-Life 2 instead of Half-Life 2: VR Mod on Steam and Discord

### ISSUE THREAD

**Issue by discomfortingsounds** [Ashok0/HL2VREssentials#11]
Is this expected behavior, and if so, is there a way to make it so it is detected as HL2:VR Mod instead? Both gameplay time and achievements on Steam are counting towards the non-VR version of the game, and it seems to be causing Cloud Save issues with HL2:VR Mod on Steam

**Comment by Ashok0** [comment]
This is due to an incorrect setting in Mod Organizer 2.  Under Tools > Settings > Workarounds, the Steam App ID must be changed from 220 to 658920.  This problem has been corrected with v1.0 of the Repack.
