### ISSUE TITLE
New maps interferences

### ISSUE THREAD

**Issue by MatteoN74** [Ashok0/HL2VREssentials#13]
With all mods enabled, there are important modifications in controls and UI. Seems to be anything from the additional maps (episodes...) causing it, but without them no HD texture is seen. For example, no VR options in the menu, no ammo counter (nearly no HUD, really) and turn is only snap with no way to change it. Advice?

**Comment by Ashok0** [comment]
Is your game installed on a drive letter other than C?  If so, make sure to update your Managed Game Path and Executables Path in MO2 under "Tools > Settings > Paths" and "Tools > Executables".   You also need to navigate to "Tools > Settings > Workarounds" and change the Steam App ID to 658920 with v0.9 of the Repack (the ID has been corrected with v1.0).

Also make sure to put Mod Organizer 2 in an unprotected folder outside of your Program Files.  Closing this issue for now but feel free to open a new ticket if you still have problems with the latest release.
