### ISSUE TITLE
ModOrganizer can't find my game executable

### ISSUE THREAD

**Issue by rmvz3** [Ashok0/HL2VREssentials#15]
I changed the path to the game folder but it seems to look for a hl2vr.exe and I have an hlvr.bat which launch an hl2.exe with proper parameters and is not recognized by MO2, so I can't install the pack.
Any way to do it manually?

Thanks

**Comment by DallenDestroyer** [comment]
I had the same issue as you but I think I figured it out. 
In the HL2VR folder, there is ModOrganizer.exe
From there, File > Manage Instance > Portable > Switch to this Instance
I haven't got further than that because im setting it up too.

**Comment by Ashok0** [comment]
Is there an HL2VR.exe file in your Half-Life 2 VR folder?  If not, try reverifying your Steam files for the game.  The most recent update for the game should add HL2VR.exe in addition to the .bat file.

**Comment by rmvz3** [comment]
Redownloading the game did the trick. Thank you.
