### ISSUE TITLE
No VPK files in zDak Total Textures Pack v5.7

### ISSUE THREAD

**Issue by a-russkikh** [Ashok0/HL2VREssentials#17]
There are no VPK files in zDaken50_Total_textures_pack.zip downloaded from ModDB. (zDaken50 Total textures pack.docx and textures2.png only)
So I`m not able to perform this steps:

-'Extract the VPK files from the zDak pack.'

-'Open 'zDak Total Textures Pack v5.7_dir.vpk' in [GCFScape]and unpack the VPK files.'
I was trying to find any of other versions of this pack but there is nothing.
Could you tell me what can I try else?

**Comment by Ashok0** [comment]
Make sure to download the Mediafire link at the bottom of the mod description:  
https://www.mediafire.com/file/09itw0czhgj5a57/zDak+Total+Textures+Pack+v5.7_066.zip/file
