### ISSUE TITLE
Minor confusion in the instructions 

### ISSUE THREAD

**Issue by discomfortingsounds** [Ashok0/HL2VREssentials#18]
It says
 "Launch MO2. Drag and drop the zDak pack ABOVE any other texture mods in the left window pane. This gives existing mods in the mod list the highest priority."
But I think the default sorting is highest priority first(I might be wrong on this, maybe that's my default setting? idk), so if you drop it above the rest, it takes highest priority.

**Comment by Ashok0** [comment]
Afaik, by default the priority should be listed from 0 (top) to 85 (bottom).   0 has the lowest priority, if you place zDak above HEP which would give it a priority of 8, it will be correctly overridden by the textures in the Repack.  The mods in the mod list will work as expected, and the zDak pack will cover textures not covered by the Repack.

**Comment by discomfortingsounds** [comment]
0 having the lowest priority is very strange to me, but it does indeed seem to be the case. 
The confusion was on my part.
