### ISSUE TITLE
HL2 Install On Different Drive.

### ISSUE THREAD

**Issue by JohnCrichton13** [Ashok0/HL2VREssentials#19]
Hi there, is there a way to point the mod app to another drive other than C: ?

I have it on a separate drive and can't work out how to change where the Mod app is looking - it's defaulting to C:?

Many thanks in anticipation,

JC.

**Comment by Ashok0** [comment]
Sure, you can point the links to another drive in Mod Organizer 2.  

1) Select Tools > Settings > Paths and update the Managed Game path to match your drive letter.
2) Select Tools > Executables > Half-Life 2 VR and update the Binary and Start in paths to match your drive letter.

**Comment by JohnCrichton13** [comment]
Hey there and many thanks for getting back to me so quickly!

I changed as you suggested but now I get a list of conflicts with the mods?!

Any ideas?

Maybe it's easier to move it to the C Drive?

**Comment by Ashok0** [comment]
That's normal, mods will always have conflicts by design.  It's because many texture mods overhaul the exact same textures.  That's the whole point of using Mod Organizer 2.  I have MO2 preconfigured with a load order that was designed to ensure that all mods will work properly despite conflicts.

**Comment by JohnCrichton13** [comment]
Ok great - many thanks once again for replying.

I'll try it all tonight!
