### ISSUE TITLE
HD Textures mod for bricks?

### ISSUE THREAD

**Issue by f00d4tehg0dz** [Ashok0/HL2VREssentials#20]
Hey there, 

I'm hoping a better texture pack for the brick walls in HL2VR is possible. The best I could find was an [abandoned project](https://gamebanana.com/wips/50936)

![Example of the low-resolution texture](https://user-images.githubusercontent.com/1635526/193462424-8a22b872-fcdd-4f73-ba77-331d9c42abc2.jpg)

**Comment by Ashok0** [comment]
I took a quick look into this.   You should be able to fix these horrible looking walls by simply deleting these low resolution textures from the HL2 HD Enhancement Project mod:

stonewall050f.*
stonewall050k.*
stonewall051a.*
stonewall051a_normal.*
stonewall051b.*
stonewall051c.*

And then make sure you have the zDak Total Textures pack installed and everything should look great.  I'll be pushing this change into v1.02 soon.
