### ISSUE TITLE
Minerva cannot be completed without console commands.

### ISSUE THREAD

**Issue by SmurgBurglar** [Ashok0/HL2VREssentials#21]
Minerva cannot be completed without no-clip as a section will not progress without killing Zombine enemies.

**Comment by Ashok0** [comment]
Thanks for reporting this issue!  Can you provide a saved game (from your Mod Organizer 2\overwrite\save folder) so I can review the problem?  And can you offer any additional information on the problem?  Are you unable to kill the Zombine enemies and when you cannot progress, is the game soft locked or does it crash to the desktop?

**Comment by SmurgBurglar** [comment]
nvm you dont need to kill zombine to progress you just need to shoot this support beam https://youtu.be/Fh9rCYufAbk?t=2266

**Comment by Ashok0** [comment]
Okay great!  Were you able to complete the entire campaign in VR?  Just curious if it's fully playable from start to finish as I haven't had time to run thru it yet.

**Comment by SmurgBurglar** [comment]
I wasn't planing to as i found some level design awful but if i do il update you.
But i did complete nightmare house and that works fine.
Also if your looking to add more custom campaigns found this list of HL2 mods but i was unable to get the ones i tried (The Citizen, Riot Act) to work as they needed files from the source sdk's and even after importing the files new problems arose.

**Comment by SmurgBurglar** [comment]
> Okay great! Were you able to complete the entire campaign in VR? Just curious if it's fully playable from start to finish as I haven't had time to run thru it yet.

I have finished Minerva it can be completed
