### ISSUE TITLE
Crash in Ravenholm due to a model/texture mod

### ISSUE THREAD

**Issue by SirViver** [Ashok0/HL2VREssentials#22]
Just a heads-up, at least on my machine the included "Half Life Alyx Cars and Combine Traincar" mod causes a CTD in and around Ravenholm. Specifically I noticed two spots:

1. In Ravenholm, right after you encounter the first fast zombie when closing in on the two-story building (d1_town_02).
2. In the train area after the Ravenholm mines where you first encounter Combine soldiers equipped with a Combine rifle (d1_town_05). After the last overhead sniper there's a small scripted fight between zombies and soldiers, and once you approach the red train car right behind that fight it will CTD.

Disabling the mod fixes the crash. Disabling all other mods and just enabling this one mod makes the crash happen again. Not sure which exact asset actually causes the issue. Someone else also had the same CTD problem running this modpack, though they haven't yet confirmed whether disabling this specific mod solves the problem for them as well. 

[Steam Discussion Thread](https://steamcommunity.com/app/658920/discussions/0/3642874410682847260/)

**Comment by Ashok0** [comment]
Hi, thanks for reporting.  Is this issue happening with v1.04 of the Repack?

**Comment by SirViver** [comment]
While I didn't download the whole 1.04 version of the pack due to its massive size, I did apply the fix outlined in the changelog (removing car002a.dx90.vtx from that mod) and can confirm this fixes the issue for me 👍
