### ISSUE TITLE
[Suggestion] Virtual Surround sound via DSOAL

### ISSUE THREAD

**Issue by ThreeDeeJay** [Ashok0/HL2VREssentials#24]
I posted this in the Flat2VR Discord sever but I figured you might wanna consider adding it here too.
This is a simple drop-in DLL replacement called DSOAL that virtualizes the game's surround sound into binaural stereo, so that you can tell when a sound is in front or behind you by sound alone. [Demo](https://youtu.be/xkG1igzlu7I)

[HL2VR_VirtualSurround_LastTested.zip](https://github.com/Ashok0/HL2VREssentials/files/10978300/HL2VR_VirtualSurround_LastTested.zip)
[HL2VR_VirtualSurround_Latest.zip](https://github.com/Ashok0/HL2VREssentials/files/10978302/HL2VR_VirtualSurround_Latest.zip) - Haven't tested it but I updated the files to the very latest DSOAL build
[Source code](https://github.com/kcat/dsoal)

Since the speaker configuration is gone from the audio options -and 7.1 never really worked as it should in source games AFAIK-, it needs `snd_surround_speakers 5` (and `snd_legacy_surround 0` if `1` doesn't work) which should be executed from the console or added somewhere in the launch parameters or config, which would make more sense if it was to be added to the mod 👀 
In case it's needed https://github.com/kcat/dsoal/blob/master/LICENSE

Someone was working on a proper 3D audio implementation using OpenAL Soft, but there haven't been updates in a while and audio is super choppy, although the dev said he'd get back to it https://youtu.be/Ey7BbdpdztY

**Comment by Ashok0** [comment]
Can't thank you enough for this.  This mod needs a serious PSA, just gave it a shot and it's an absolute gamechanger!  Will be adding this to the next release along with my upcoming Black Mesa Source VR mod.
