### ISSUE TITLE
Installing zDak Total Textures Pack v5.7 causes the SteamVR menu in HMD to freeze the entire VR session

### ISSUE THREAD

**Issue by trillex** [Ashok0/HL2VREssentials#25]
This is an odd one I can't seem to find anyone else having issues with. 

When using this pack together with zDak, I am getting a complete freeze of the entire HMD when I attempt to open up the SteamVR menu (the dashboard thing, not sure of the correct term). It is 100% reproducable, even on the main menu. It will also cause the computer to almost entirely lock up, with the only way to stop it being to either attempt to try and get out of it trying to open the dashboard or kill Half-Life 2 entirely. 

But, if I disable the mod (or haven't installed it at all), the game runs just fine and the dashboard pops up without any issue. This is both with and without the EP1 + EP2 assets. 

The game's performance also seems to be questionable at best with the zDak installed, hovering around ~50, with a beefy rig, that averages 144 fps without HL2VREssentials and ~72 with it. 

The reason I mention the above, is that I haven't seen _anyone_ mention this issue so it must be something strange going on, on my end. 

The rig is a i7-13700KF, 3080 and DDR5-4800 at 32 GB, using Valve Index at SS 150%. Windows 10, installed this weekend. 

I am not sure what else I can do, other than just not play with zDak, but I just wanted that first run in VR to be perfect. :)

**Comment by Ashok0** [comment]
That's very odd as no one has ever reported any issues with zDak with this repack, and your setup is actually better than mine.   It must be something specific on your end. A few things to try...

1) Does zDak work for you with the flat version of Half-Life 2?
2) Does zDak work for you in VR if you install it manually using the \hlvr\custom folder?
3) Does your HMD work fine if you install other textures mods manually through MO2?
4) Have you tried deleting half of the zDak files as a test just to see if any of the textures will work?

**Comment by trillex** [comment]
Slept on it and had a hunch that I should try it on another SSD before digging deep into this. 

I moved it all over to my C drive, making sure that it isn't in program files and now I'm getting 144 fps constantly with zDak enabled and the dashboard doesn't freeze up everything. 

I have absolutely no idea on how to explain this behaviour, other than that the first SSD must be dying, although I have never had any issues with it to suggest that.. 

No, I have no idea. 

I will close this issue, it's not an issue with the game or your mod, as far as I can figure out.
