### ISSUE TITLE
Request: Apply Mods, Then Launch Game Through SteamVR

### ISSUE THREAD

**Issue by GT500org** [Ashok0/HL2VREssentials#3]
I'd rather not launch the game through Mod Organizer. Can you give us a way to install/apply the mods to the game so that it can be launched through SteamVR instead?

**Comment by stanvx** [comment]
You should be able to achieve this through making a desktop shortcut for the config within Mod Organizer 2 and then adding it as a Non-Steam game inside Steam and allowing it to show within SteamVR through its properties.

**Comment by Ashok0** [comment]
Like a above poster mentioned, this can be achieved with a shortcut.  Closing this issue.
