### ISSUE TITLE
Don't use google drive.

### ISSUE THREAD

**Issue by BeigeAnimal** [Ashok0/HL2VREssentials#4]
Google drive has a limit if too many people download a file within 24 hours, use literally almost anything else, or at least provide a mirror for something like mega.

**Comment by GitHubUsername1** [comment]
Please provide a mirror link.

**Comment by TIE-INTERCEPTOR** [comment]
found an alternative way in discord,  get jdownloader2 http://jdownloader.org/jdownloader2 ,  install it, then get https://t.co/gvIp9BRZZV < this download link, open it with jdownloader and you are good to go, it will download it... it's huge so patience.

**Comment by mathbrasil** [comment]
Its possible to bypass Google drive limit by this way:

1. With de google drive link opened, click on three dots in the upper right corner and click on "add to starred"
2. Go back to your drive and to the "starred" area
3.  To work, you will need to select 2 starred items holding shift and click on download. 

After that, just wait, the download will take a while to start, but it will work

Sorry for bad english, hope it help

**Comment by BeigeAnimal** [comment]
> Its possible to bypass Google drive limit by this way:
> 
>     1. With de google drive link opened, click on three dots in the upper right corner and click on "add to starred"
> 
>     2. Go back to your drive and to the "starred" area
> 
>     3. To work, you will need to select 2 starred items holding shift and click on download.
> 
> 
> After that, just wait, the download will take a while to start, but it will work
> 
> Sorry for bad english, hope it help

you couldn't even star it is the thing, clicking the link would bring you directly to the 24 hour limit page

**Comment by mathbrasil** [comment]
> > Its possible to bypass Google drive limit by this way:
> > ```
> > 1. With de google drive link opened, click on three dots in the upper right corner and click on "add to starred"
> > 
> > 2. Go back to your drive and to the "starred" area
> > 
> > 3. To work, you will need to select 2 starred items holding shift and click on download.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, just wait, the download will take a while to start, but it will work
> > Sorry for bad english, hope it help
> 
> you couldn't even star it is the thing, clicking the link would bring you directly to the 24 hour limit page

When i open the link ([https://drive.google.com/file/d/1VYIpXoqdFKrUVWgkBeqd89UNi3zkch4q/view), i get this [screen](https://prnt.sc/PPFiAATnMLKq) with the star option (screenshot its in pt-BR)

**Comment by KrisSodroski** [comment]
Real work around here.  I wouldn't download jdownloader2.  Have no clue what that sketchy s*** is. 

`Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.`

**Comment by qant** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 
> `Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.`

Heh so funny... ) the devs created a restriction to prevent overhead but force user to create even more overhead with creating a zip! instead just give it to download lol )))

Thank you for tip! qa testers in google are bad =)

**Comment by BeigeAnimal** [comment]
> > > Its possible to bypass Google drive limit by this way:
> > > ```
> > > 1. With de google drive link opened, click on three dots in the upper right corner and click on "add to starred"
> > > 
> > > 2. Go back to your drive and to the "starred" area
> > > 
> > > 3. To work, you will need to select 2 starred items holding shift and click on download.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After that, just wait, the download will take a while to start, but it will work
> > > Sorry for bad english, hope it help
> > 
> > 
> > you couldn't even star it is the thing, clicking the link would bring you directly to the 24 hour limit page
> 
> When i open the link ([https://drive.google.com/file/d/1VYIpXoqdFKrUVWgkBeqd89UNi3zkch4q/view), i get this [screen](https://prnt.sc/PPFiAATnMLKq) with the star option (screenshot its in pt-BR)

You get that page because the 24 download limit wasn't reached...
Clicking the link from the Readme while the limit is actually active will show something else

**Comment by BeigeAnimal** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 
> `Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.`

JDownloader is a well known piece of software, admittedly it looks dated but it is open source

**Comment by BeigeAnimal** [comment]
> > > Its possible to bypass Google drive limit by this way:
> > > ```
> > > 1. With de google drive link opened, click on three dots in the upper right corner and click on "add to starred"
> > > 
> > > 2. Go back to your drive and to the "starred" area
> > > 
> > > 3. To work, you will need to select 2 starred items holding shift and click on download.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After that, just wait, the download will take a while to start, but it will work
> > > Sorry for bad english, hope it help
> > 
> > 
> > you couldn't even star it is the thing, clicking the link would bring you directly to the 24 hour limit page
> 
> When i open the link ([https://drive.google.com/file/d/1VYIpXoqdFKrUVWgkBeqd89UNi3zkch4q/view), i get this [screen](https://prnt.sc/PPFiAATnMLKq) with the star option (screenshot its in pt-BR)

The day I made this issue, clicking the link would take me directly to the 24 hours limit page with no option to star, because I know about the google drive workarounds and that was my first thought. Google drive may be inconsistent with how the warnings work tbh, since I've had similar experiences in the past. 
still a mirror is needed

**Comment by TIE-INTERCEPTOR** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 
> `Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.`

the work around using the jdownloader2 software I got straight up from the flat to vr discord , you can check yourself
if you don't belive me , I have no skin on this game, I'm just sharing the info that worked for me.

https://discord.com/channels/747967102895390741/1020466377032728647

**Comment by Ashok0** [comment]
Download links have been moved to a new host.
