### ISSUE TITLE
Google drive link dead for two days now.

### ISSUE THREAD

**Issue by TIE-INTERCEPTOR** [Ashok0/HL2VREssentials#5]
Google link is dead, has been dead for more than 24h , can't find the file anywhere else, google drive link is locked due to overuse

please upload somewhere else! need mirror options, please.

**Comment by TIE-INTERCEPTOR** [comment]
found an alternative way,  get jdownloader2 http://jdownloader.org/jdownloader2 ,  install it, then get https://t.co/gvIp9BRZZV < this download link, open it with jdownloader and you are good to go, it will download it... it's huge so patience.

**Comment by KrisSodroski** [comment]
Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.

Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.

**Comment by webhead2oo9** [comment]
I'm rehosting it for the time being at https://vrdiscord.com/HL2VR_MO2.rar

I'll host it as long as I have the bandwith

**Comment by HamzaETTH** [comment]
> I'm rehosting it for the time being at https://vrdiscord.com/HL2VR_MO2.rar
> 
> I'll host it as long as I have the bandwith

thanks, can you host [EP1+2 Assets.rar](https://drive.google.com/file/d/1g_QkR3Q35AnTKcdPfPNMNj5helwAIz2w/view?usp=sharing) too ?

**Comment by TIE-INTERCEPTOR** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 
> Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.

it's straight up from the discord of the guys making the mods, you can check for yourself. It might look dodgy as f but I tried it and it worked. Anyway, 

you can check the thread on the help on the flatscreen to VR discord  > 
  https://discord.com/channels/747967102895390741/1020466377032728647

**Comment by webhead2oo9** [comment]
> > I'm rehosting it for the time being at https://vrdiscord.com/HL2VR_MO2.rar
> > I'll host it as long as I have the bandwith
> 
> thanks, can you host [EP1+2 Assets.rar](https://drive.google.com/file/d/1g_QkR3Q35AnTKcdPfPNMNj5helwAIz2w/view?usp=sharing) too ?

Sure thing, https://vrdiscord.com/EP12Assets.rar

**Comment by MiniGrief** [comment]
> Real work around here. I wouldn't download jdownloader2. Have no clue what that sketchy s*** is.
> 
> Add it as a shortcut to your Google drive (+ button with GDrive logo on the top right) then select two files in your Google drive, one of them being the essentials mod pack and press download. They will be put together in a zip file and it bypasses the download limit.

JDownloader does seem sketchy but it's main purpose is to download large archive files which are split into parts. It's used pretty commonly in 'not so legal' game downloading. It is safe. However, that workaround you mentioned will also work so do whatever you feel comfortable with.

**Comment by Flux001337** [comment]
> I'm rehosting it for the time being at https://vrdiscord.com/HL2VR_MO2.rar
> 
> I'll host it as long as I have the bandwith


> 
> Sure thing, https://vrdiscord.com/EP12Assets.rar


You are my hero! Thank's

**Comment by Ashok0** [comment]
Download links have been moved to a new host.
