### ISSUE TITLE
Crowbar swing sound missing 

### ISSUE THREAD

**Issue by discomfortingsounds** [Ashok0/HL2VREssentials#7]
The crowbar swing sound is missing(swinging in the air sound, not the hit sound). I've tried disabling the sound mod and it works that way. Is there a way to get the swinging sound back without disabling the sound mod altogether?

**Comment by Ashok0** [comment]
Fixed with v1.0.  This was due to HL2 MMod Improved Sounds which has been removed from the mod list.
