### ISSUE TITLE
Directions from mirror files - and "AI disabled"

### ISSUE THREAD

**Issue by hobyvh** [Ashok0/HL2VREssentials#8]
1. The files can't be downloaded directly from Gdrive and mirror files I found don't exactly match what I'm seeing in the directions. What I ended up with is a plugin for Mod Organizer (MO) to know what HL2VR is, the extracted Assets multipart rars, the HL2 HEP mod, and MO installed.
2. Through trial and error I was able to figure out that the plugin needed to be added to the MO installation and the HL2 HEP folder needed to be put into the Modding/MO2/mods/ folder.

Now if I launch, things look slightly different and I see an "AI disabled" message displayed, with no NPCs moving at all.

**Comment by Ashok0** [comment]
Download links have been updated with a new release and moved to a new host.  

If you are getting "AI Disabled" messages, open the console and enter the following commands:
ai_norebuildgraph 1
ai_resume

and then reload your saved game.   That should hopefully fix it.
