### ISSUE TITLE
slower movement speed

### ISSUE THREAD

**Issue by djsolidsnake86** [Ashok0/HL2VREssentials#9]
hello, i was using these parameters 

You can find autoexec.cfg in Half-Life 2 VR/hlvr/cfg. Then, add 2 lines.

hl2_normspeed 130
hl2_sprintspeed 220 

for lower movement speed, the problem is with this mod the parameters not work anymore
any solution?

**Comment by Ashok0** [comment]
The default autoexec.cfg file in your Steam folder is not used by MO2.  Be sure to place autoexec.cfg settings in \mods\Config File\cfg\autoexec.cfg which is found in your MO2 folder.
